Microbe/Models/ProjectInformationModels/ClientProjects.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Microbe.Models.ProjectInformationModels
{
    public class ClientProjects
    {
        public int id { get; set; }
        public string ClientName { get; set; }
        public string ProjectName { get; set; }
        public string Report { get; set; }
        public string OutputToScreen { get; set; }
        public string Genwiz { get; set; }
        public ICollection<ClientProjectReports> ClientProjectReports { get; set; }
    }
}

Microbe/Controllers/ProjectInformationControllers/ClientProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microbe.Data;
using Microbe.Models.ProjectInformationModels;

namespace Microbe.Controllers.ProjectInformationControllers
{
    public class ClientProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientProjectsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ClientProjects
        public async Task<IActionResult> Index(string searchString)
        {
            var Clients = from c in _context.ClientProjects
                         select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                Clients = Clients.Where(s => s.ClientName.Contains(searchString));
            }

            return View(await _context.ClientProjects.ToListAsync());
        }

        // GET: ClientProjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientProjects = await _context.ClientProjects
                .SingleOrDefaultAsync(m => m.id == id);
            if (clientProjects == null)
            {
                return NotFound();
            }

            return View(clientProjects);
        }

        // GET: ClientProjects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ClientProjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,ClientName,ProjectName,Report,OutputToScreen,Genwiz")] ClientProjects clientProjects)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clientProjects);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(clientProjects);
        }

        // GET: ClientProjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientProjects = await _context.ClientProjects.SingleOrDefaultAsync(m => m.id == id);
            if (clientProjects == null)
            {
                return NotFound();
            }
            return View(clientProjects);
        }

        // POST: ClientProjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,ClientName,ProjectName,Report,OutputToScreen,Genwiz")] ClientProjects clientProjects)
        {
            if (id != clientProjects.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clientProjects);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientProjectsExists(clientProjects.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(clientProjects);
        }

        // GET: ClientProjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientProjects = await _context.ClientProjects
                .SingleOrDefaultAsync(m => m.id == id);
            if (clientProjects == null)
            {
                return NotFound();
            }

            return View(clientProjects);
        }

        // POST: ClientProjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var clientProjects = await _context.ClientProjects.SingleOrDefaultAsync(m => m.id == id);
            _context.ClientProjects.Remove(clientProjects);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientProjectsExists(int id)
        {
            return _context.ClientProjects.Any(e => e.id == id);
        }
    }
}

Microbe/Views/ClientProjects/Create.cshtml
@model Microbe.Models.ProjectInformationModels.ClientProjects

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>ClientProjects</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label"></label>
                <input asp-for="ProjectName" class="form-control" />
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Report" class="control-label"></label>
                <input asp-for="Report" class="form-control" />
                <span asp-validation-for="Report" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OutputToScreen" class="control-label"></label>
                <input asp-for="OutputToScreen" class="form-control" />
                <span asp-validation-for="OutputToScreen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genwiz" class="control-label"></label>
                <input asp-for="Genwiz" class="form-control" />
                <span asp-validation-for="Genwiz" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Microbe/Views/ClientProjects/Delete.cshtml
@model Microbe.Models.ProjectInformationModels.ClientProjects

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClientProjects</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClientName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Report)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Report)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OutputToScreen)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OutputToScreen)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genwiz)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genwiz)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Microbe/Views/ClientProjects/Details.cshtml
@model Microbe.Models.ProjectInformationModels.ClientProjects

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>ClientProjects</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClientName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Report)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Report)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OutputToScreen)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OutputToScreen)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genwiz)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genwiz)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Microbe/Views/ClientProjects/Edit.cshtml
@model Microbe.Models.ProjectInformationModels.ClientProjects

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ClientProjects</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label"></label>
                <input asp-for="ProjectName" class="form-control" />
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Report" class="control-label"></label>
                <input asp-for="Report" class="form-control" />
                <span asp-validation-for="Report" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OutputToScreen" class="control-label"></label>
                <input asp-for="OutputToScreen" class="form-control" />
                <span asp-validation-for="OutputToScreen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genwiz" class="control-label"></label>
                <input asp-for="Genwiz" class="form-control" />
                <span asp-validation-for="Genwiz" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Microbe/Views/ClientProjects/Index.cshtml
@model IEnumerable<Microbe.Models.ProjectInformationModels.ClientProjects>

@{
    ViewData["Title"] = "Client / Projects";
}

<h2>Index</h2>
<br />
<br />
<br />
<br />


<form asp-controller="ClientProjects" asp-action="Index">
    <p>
        Client: <input type="text" name="searchString">
        <input type="submit" value="Filter" />
    </p>
</form>
<p>
    <a asp-action="Create">Create New</a>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Report)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OutputToScreen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genwiz)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ClientName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Report)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OutputToScreen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genwiz)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>