Microbe/Models/ReportModels/ReportSections.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Microbe.Models.ReportSections
{
    public class ReportSections
    {
        [Key]
        public int ReportSectionID { get; set; }
        public int ReportDefinitionID { get; set; }
        public int SectionOrder { get; set; }
        public string SectionTitle { get; set; }
        public string SectionDesc { get; set; }
        public string ModifiedBy { get; set; }
        public string createDate { get; set; }
        public string modifiedDate { get; set; }
    }
}

Microbe/Models/ReportModels/ReportTitlePage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace Microbe.Models.ReportModels
{
    public class ReportTitlePage
    {
        [Key]
        public int ReportTitlePageID { get; set; }
        public string ProjectID { get; set; }
        public string ReportType { get; set; }
        public string ReportTitle { get; set; }
        public string ReportDate { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public string AddressLine5 { get; set; }
        public string ContactEmail { get; set; }
        public string ProjectText { get; set; }
        public string ReportComments { get; set; }
    }
}

Microbe/Controllers/ReportSectionFiguresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microbe.Data;
using Microbe.Models.ReportModels;

namespace Microbe.Controllers
{
    public class ReportSectionFiguresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReportSectionFiguresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ReportSectionFigures
        public async Task<IActionResult> Index()
        {
            return View(await _context.ReportSectionFigures.ToListAsync());
        }

        // GET: ReportSectionFigures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportSectionFigures = await _context.ReportSectionFigures
                .SingleOrDefaultAsync(m => m.ReportSectionFigureID == id);
            if (reportSectionFigures == null)
            {
                return NotFound();
            }

            return View(reportSectionFigures);
        }

        // GET: ReportSectionFigures/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ReportSectionFigures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReportSectionFigureID,ReportSectionID,SectionFigureOrder,FigureType,FigureDesc,FigureSuffix")] ReportSectionFigures reportSectionFigures)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reportSectionFigures);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reportSectionFigures);
        }

        // GET: ReportSectionFigures/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportSectionFigures = await _context.ReportSectionFigures.SingleOrDefaultAsync(m => m.ReportSectionFigureID == id);
            if (reportSectionFigures == null)
            {
                return NotFound();
            }
            return View(reportSectionFigures);
        }

        // POST: ReportSectionFigures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReportSectionFigureID,ReportSectionID,SectionFigureOrder,FigureType,FigureDesc,FigureSuffix")] ReportSectionFigures reportSectionFigures)
        {
            if (id != reportSectionFigures.ReportSectionFigureID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reportSectionFigures);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReportSectionFiguresExists(reportSectionFigures.ReportSectionFigureID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reportSectionFigures);
        }

        // GET: ReportSectionFigures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportSectionFigures = await _context.ReportSectionFigures
                .SingleOrDefaultAsync(m => m.ReportSectionFigureID == id);
            if (reportSectionFigures == null)
            {
                return NotFound();
            }

            return View(reportSectionFigures);
        }

        // POST: ReportSectionFigures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reportSectionFigures = await _context.ReportSectionFigures.SingleOrDefaultAsync(m => m.ReportSectionFigureID == id);
            _context.ReportSectionFigures.Remove(reportSectionFigures);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReportSectionFiguresExists(int id)
        {
            return _context.ReportSectionFigures.Any(e => e.ReportSectionFigureID == id);
        }
    }
}

Microbe/Controllers/ReportSectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microbe.Data;
using Microbe.Models.ReportSections;

namespace Microbe.Controllers
{
    public class ReportSectionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReportSectionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ReportSections
        public async Task<IActionResult> Index()
        {
            return View(await _context.ReportSections.ToListAsync());
        }

        // GET: ReportSections/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportSections = await _context.ReportSections
                .SingleOrDefaultAsync(m => m.ReportSectionID == id);
            if (reportSections == null)
            {
                return NotFound();
            }

            return View(reportSections);
        }

        // GET: ReportSections/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ReportSections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReportSectionID,ReportDefinitionID,SectionOrder,SectionTitle,SectionDesc,ModifiedBy,createDate,modifiedDate")] ReportSections reportSections)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reportSections);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reportSections);
        }

        // GET: ReportSections/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportSections = await _context.ReportSections.SingleOrDefaultAsync(m => m.ReportSectionID == id);
            if (reportSections == null)
            {
                return NotFound();
            }
            return View(reportSections);
        }

        // POST: ReportSections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReportSectionID,ReportDefinitionID,SectionOrder,SectionTitle,SectionDesc,ModifiedBy,createDate,modifiedDate")] ReportSections reportSections)
        {
            if (id != reportSections.ReportSectionID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reportSections);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReportSectionsExists(reportSections.ReportSectionID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reportSections);
        }

        // GET: ReportSections/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportSections = await _context.ReportSections
                .SingleOrDefaultAsync(m => m.ReportSectionID == id);
            if (reportSections == null)
            {
                return NotFound();
            }

            return View(reportSections);
        }

        // POST: ReportSections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reportSections = await _context.ReportSections.SingleOrDefaultAsync(m => m.ReportSectionID == id);
            _context.ReportSections.Remove(reportSections);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReportSectionsExists(int id)
        {
            return _context.ReportSections.Any(e => e.ReportSectionID == id);
        }
    }
}

Microbe/Controllers/ReportTitlePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microbe.Data;
using Microbe.Models.ReportModels;

namespace Microbe.Controllers
{
    public class ReportTitlePageController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReportTitlePageController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ReportTitlePage
        public async Task<IActionResult> Index()
        {
            return PartialView(_context.ReportTitlePages.ToList());
        }

        // GET: ReportTitlePage/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ReportTitlePage = await _context.ReportTitlePages
                .SingleOrDefaultAsync(m => m.ReportTitlePageID == id);
            if (ReportTitlePage == null)
            {
                return NotFound();
            }

            return PartialView(ReportTitlePage);
        }

    }
}

Microbe/Views/ReportSections/Create.cshtml
@model Microbe.Models.ReportSections.ReportSections

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Report Sections</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ReportDefinitionID" class="control-label"></label>
                <input asp-for="ReportDefinitionID" class="form-control" />
                <span asp-validation-for="ReportDefinitionID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SectionOrder" class="control-label"></label>
                <input asp-for="SectionOrder" class="form-control" />
                <span asp-validation-for="SectionOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SectionTitle" class="control-label"></label>
                <input asp-for="SectionTitle" class="form-control" />
                <span asp-validation-for="SectionTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SectionDesc" class="control-label"></label>
                <input asp-for="SectionDesc" class="form-control" />
                <span asp-validation-for="SectionDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedBy" class="control-label"></label>
                <input asp-for="ModifiedBy" class="form-control" />
                <span asp-validation-for="ModifiedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="createDate" class="control-label"></label>
                <input asp-for="createDate" class="form-control" />
                <span asp-validation-for="createDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="modifiedDate" class="control-label"></label>
                <input asp-for="modifiedDate" class="form-control" />
                <span asp-validation-for="modifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Microbe/Views/ReportSections/Delete.cshtml
@model Microbe.Models.ReportSections.ReportSections

@{
    ViewData["Title"] = "Delete Report Section";
}

<h2>Delete Report Section</h2>

<h3>Are you sure you want to delete this report section?</h3>
<div>
    <h4>ReportSections</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReportDefinitionID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReportDefinitionID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SectionOrder)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SectionOrder)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SectionTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SectionTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SectionDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SectionDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.createDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.createDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.modifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.modifiedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReportSectionID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Microbe/Views/ReportSections/Details.cshtml
@model Microbe.Models.ReportSections.ReportSections

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>ReportSections</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReportDefinitionID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReportDefinitionID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SectionOrder)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SectionOrder)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SectionTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SectionTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SectionDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SectionDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.createDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.createDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.modifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.modifiedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ReportSectionID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Microbe/Views/ReportSections/Edit.cshtml
@model Microbe.Models.ReportSections.ReportSections

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ReportSections</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReportSectionID" />
            <div class="form-group">
                <label asp-for="ReportDefinitionID" class="control-label"></label>
                <input asp-for="ReportDefinitionID" class="form-control" />
                <span asp-validation-for="ReportDefinitionID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SectionOrder" class="control-label"></label>
                <input asp-for="SectionOrder" class="form-control" />
                <span asp-validation-for="SectionOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SectionTitle" class="control-label"></label>
                <input asp-for="SectionTitle" class="form-control" />
                <span asp-validation-for="SectionTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SectionDesc" class="control-label"></label>
                <input asp-for="SectionDesc" class="form-control" />
                <span asp-validation-for="SectionDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedBy" class="control-label"></label>
                <input asp-for="ModifiedBy" class="form-control" />
                <span asp-validation-for="ModifiedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="createDate" class="control-label"></label>
                <input asp-for="createDate" class="form-control" />
                <span asp-validation-for="createDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="modifiedDate" class="control-label"></label>
                <input asp-for="modifiedDate" class="form-control" />
                <span asp-validation-for="modifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Microbe/Views/ReportSections/Index.cshtml
@model IEnumerable<Microbe.Models.ReportSections.ReportSections>

@{
    ViewData["Title"] = "Report Sections";
}

<h2>Report Sections</h2>


<table class="table">
    <thead>
        <tr>
            <!--<th>        @Html.DisplayNameFor(model => model.ReportDefinitionID)    </th>-->
            <th>
                @Html.DisplayNameFor(model => model.SectionOrder)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SectionTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SectionDesc)
            </th>
            <th colspan="30"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <!--<td>
        @Html.DisplayFor(modelItem => item.ReportDefinitionID)
    </td>-->
            <td>
                @Html.DisplayFor(modelItem => item.SectionOrder)
            </td>
            <td>
                <a asp-controller="ReportSectionFigures" asp-action="Index" asp-route-id="@item.ReportSectionID">@Html.DisplayFor(modelItem => item.SectionTitle)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SectionDesc)
            </td>
            
            <td>
                <nbsp><a asp-action="Edit" asp-route-id="@item.ReportSectionID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ReportSectionID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ReportSectionID">Delete</a></nbsp>
            </td>
        </tr>
        }
    </tbody>

</table>
<p>
    <a asp-action="Create">Create New Report Section</a>
</p>

Microbe/Views/ReportSections/_ReportFront.cshtml
@model IEnumerable<Microbe.Models.NGSReportParts.NGS_GenClassificationResults>


<h3></h3><!--Table 4 Top Genus Classification Results -->
<table><tr><td class="FirstLabel">Table 4:</td><td class="FirstColumn">Top genera classification results  for sample T5-D3-0618. Additional identified genera are included in the accompanying Excel data file.</td></tr></table>
<table class="full">
    <thead>
        <tr class="RedBackLabelBottom">
            <td width="25%">Classification</td>
            <td width="13%">Number of Reads</td>
            <td width="12%">% Total Reads</td>
            <td>Description</td>
        </tr>
     </thead>
     <tbody>
        @foreach (var item in Model)
        {
                <tr>
                    <!--<td>
                        @Html.DisplayFor(modelItem => item.Genus)
                    </td>-->
                    <td>
                        @Html.DisplayFor(modelItem => item.numHits)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.percentHits)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GenusDescription)
                    </td>
                </tr>
        }
    </tbody>
    </table>

Microbe/Views/ReportSections/_ReportTitlePage.cshtml
@model Microbe.Models.ReportModels.ReportTitlePage

@{
    ViewData["Title"] = "NGS Report";
}

<h1>Site Logic Report</h1>
<hr class="redline" />
<h2><i>@Html.DisplayFor(model => model.ReportTitle)</i></h2>
<table class="full" cellspacing="20">
    <tr><td class="FirstLabel">Contact:</td><td class="FirstColumn">@Html.DisplayFor(model => model.ContactName)</td>
        <td></td>
        <td class="SecondLabel">Phone:</td><td class="SecondColumn">@Html.DisplayFor(model => model.ContactPhone)</td>
    </tr>
    <tr>
        <td class="FirstLabel">Address:</td><td class="FirstColumn">@Html.DisplayFor(model => model.AddressLine1)<BR />@Html.DisplayFor(model => model.AddressLine2)<BR />@Html.DisplayFor(model => model.AddressLine3)<BR />@Html.DisplayFor(model => model.AddressLine4)<BR />@Html.DisplayFor(model => model.AddressLine5)</td>
        <td></td>
        <td class="SecondLabel">Email:</td><td class="SecondColumn">@Html.DisplayFor(model => model.ContactEmail)</td></tr>
</table>
<table class="full">
    <tr>
        <td width="50%"><table class="full"><tr class="RedBackLabel"><td>MI Identifier:</td><td class="CenterData">@Html.DisplayFor(model => model.ProjectID)</td></tr></table></td>
        <td class="SecondLabel" width="10%">Report Date:</td>
        <td class="SecondColumn">@Html.DisplayFor(model => model.ReportDate)</td>
    </tr>
</table>
<table class="full">
    <tr><td class="FirstLabel" width="20%">Project:</td><td></td><td class="FirstColumn">@Html.DisplayFor(model => model.ProjectText)</td></tr>
    <tr><td class="FirstLabel" width="20%">Comments:</td><td></td><td class="FirstColumn">@Html.DisplayFor(model => model.ReportComments)</td></tr>
</table>