Microbe/Models/ProjectInformationModels/LIMS_Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Microbe.Models.ProjectInformationModels
{
    public class LIMS_Client
    {
       [Key]
       public int ClientID  { get; set; }
        [Display(Name = "Display Name")]
        public string DisplayName { get; set; }
        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }
        [Display(Name = "Notes")]
        public string ClientNotes { get; set; }
        [Display(Name = "Active?")]
        public Boolean active { get; set; }
        public Int64 primaryinvname { get; set; }
       public Int64 secondaryinvname { get; set; }
       public string DateAdded { get; set; }
    }
}

Microbe/Controllers/ProjectInformationControllers/LIMS_ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microbe.Data;
using Microbe.Models.ProjectInformationModels;

namespace Microbe.Controllers.ProjectInformationControllers
{
    public class LIMS_ClientController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LIMS_ClientController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LIMS_Client
        public async Task<IActionResult> Index(string searchString)
        {
            var lIMS_Client = from b in _context.LIMS_Client
                                select b;
            
            if (searchString == null)
            {
                lIMS_Client = lIMS_Client.Where(s => s.DisplayName != "");
            }
            else
            {
                lIMS_Client = lIMS_Client.Where(s => s.DisplayName.Contains(searchString));
            }
            lIMS_Client = lIMS_Client.OrderBy(s => s.DisplayName);
            

            if (lIMS_Client == null)
            {
                return NotFound();
            }
            return View(await lIMS_Client.AsNoTracking().Take(50).ToListAsync());
        }

        // GET: LIMS_Client/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lIMS_Client = await _context.LIMS_Client
                .SingleOrDefaultAsync(m => m.ClientID == id);
            if (lIMS_Client == null)
            {
                return NotFound();
            }

            return View(lIMS_Client);
        }

        // GET: LIMS_Client/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LIMS_Client/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientID,DisplayName,CompanyName,ClientNotes,active,primaryinvname,secondaryinvname,DateAdded")] LIMS_Client lIMS_Client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lIMS_Client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(lIMS_Client);
        }

        // GET: LIMS_Client/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lIMS_Client = await _context.LIMS_Client.SingleOrDefaultAsync(m => m.ClientID == id);
            if (lIMS_Client == null)
            {
                return NotFound();
            }
            return View(lIMS_Client);
        }

        // POST: LIMS_Client/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClientID,DisplayName,CompanyName,ClientNotes,active,primaryinvname,secondaryinvname,DateAdded")] LIMS_Client lIMS_Client)
        {
            if (id != lIMS_Client.ClientID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lIMS_Client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LIMS_ClientExists(lIMS_Client.ClientID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lIMS_Client);
        }

        // GET: LIMS_Client/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lIMS_Client = await _context.LIMS_Client
                .SingleOrDefaultAsync(m => m.ClientID == id);
            if (lIMS_Client == null)
            {
                return NotFound();
            }

            return View(lIMS_Client);
        }

        // POST: LIMS_Client/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lIMS_Client = await _context.LIMS_Client.SingleOrDefaultAsync(m => m.ClientID == id);
            _context.LIMS_Client.Remove(lIMS_Client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LIMS_ClientExists(int id)
        {
            return _context.LIMS_Client.Any(e => e.ClientID == id);
        }
    }
}

Microbe/Views/LIMS_Client/Create.cshtml
@model Microbe.Models.ProjectInformationModels.LIMS_Client

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>LIMS_Client</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DisplayName" class="control-label"></label>
                <input asp-for="DisplayName" class="form-control" />
                <span asp-validation-for="DisplayName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientNotes" class="control-label"></label>
                <input asp-for="ClientNotes" class="form-control" />
                <span asp-validation-for="ClientNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="active" class="control-label"></label>
                <input asp-for="active" class="form-control" />
                <span asp-validation-for="active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="primaryinvname" class="control-label"></label>
                <input asp-for="primaryinvname" class="form-control" />
                <span asp-validation-for="primaryinvname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="secondaryinvname" class="control-label"></label>
                <input asp-for="secondaryinvname" class="form-control" />
                <span asp-validation-for="secondaryinvname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateAdded" class="control-label"></label>
                <input asp-for="DateAdded" class="form-control" />
                <span asp-validation-for="DateAdded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Microbe/Views/LIMS_Client/Delete.cshtml
@model Microbe.Models.ProjectInformationModels.LIMS_Client

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LIMS_Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DisplayName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DisplayName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ClientNotes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClientNotes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.active)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.active)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.primaryinvname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.primaryinvname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.secondaryinvname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.secondaryinvname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ClientID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Microbe/Views/LIMS_Client/Details.cshtml
@model Microbe.Models.ProjectInformationModels.LIMS_Client

@{
    ViewData["Title"] = "Details";
}
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<br />
<br />
<br />
<br />
@if (SignInManager.IsSignedIn(User))
{

    <h2>Details</h2>

    <div>
        <h4>LIMS_Client</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.DisplayName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.DisplayName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CompanyName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CompanyName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ClientNotes)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ClientNotes)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.active)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.active)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.primaryinvname)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.primaryinvname)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.secondaryinvname)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.secondaryinvname)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DateAdded)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.DateAdded)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.ClientID">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
}
else
{
    <h2>Please Login to continue</h2>
}

Microbe/Views/LIMS_Client/Edit.cshtml
@model Microbe.Models.ProjectInformationModels.LIMS_Client

@{
    ViewData["Title"] = "Edit";
}
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<br />
<br />
<br />
<br />
@if (SignInManager.IsSignedIn(User))
{

    <h2>Edit</h2>

    <h4>LIMS_Client</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ClientID" />
                <div class="form-group">
                    <label asp-for="DisplayName" class="control-label"></label>
                    <input asp-for="DisplayName" class="form-control" />
                    <span asp-validation-for="DisplayName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CompanyName" class="control-label"></label>
                    <input asp-for="CompanyName" class="form-control" />
                    <span asp-validation-for="CompanyName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ClientNotes" class="control-label"></label>
                    <input asp-for="ClientNotes" class="form-control" />
                    <span asp-validation-for="ClientNotes" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="active" class="control-label"></label>
                    <input asp-for="active" class="form-control" />
                    <span asp-validation-for="active" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="primaryinvname" class="control-label"></label>
                    <input asp-for="primaryinvname" class="form-control" />
                    <span asp-validation-for="primaryinvname" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="secondaryinvname" class="control-label"></label>
                    <input asp-for="secondaryinvname" class="form-control" />
                    <span asp-validation-for="secondaryinvname" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DateAdded" class="control-label"></label>
                    <input asp-for="DateAdded" class="form-control" />
                    <span asp-validation-for="DateAdded" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
            }
            else
            {
    <h2>Please Login to continue...</h2>
            }

Microbe/Views/LIMS_Client/Index.cshtml
@model IEnumerable<Microbe.Models.ProjectInformationModels.LIMS_Client>

@{
    ViewData["Title"] = "Clients";
}
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<br />
<br />
<br />
<br />
@if (SignInManager.IsSignedIn(User))
{

        <h2>Clients</h2>

        <p>
            Client List is maintained in the LIMS system
        </p>
        <form asp-controller="LIMS_Client" asp-action="Index">
            <p>
                Search for Client: <input type="text" name="SearchString">
                <input type="submit" value="Filter" />
            </p>
        </form>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.DisplayName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CompanyName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ClientNotes)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.active)
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a asp-controller="LIMS_Branches" asp-action="Index" asp-route-id="@item.ClientID">@Html.DisplayFor(modelItem => item.DisplayName)</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CompanyName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ClientNotes)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.active)
                        </td>

                        <td>
                            <!--<a asp-action="Edit" asp-route-id="@item.ClientID">Edit</a>&nbsp;|&nbsp;-->
                            <a asp-action="Details" asp-route-id="@item.ClientID">Details</a>
                            <!--&nbsp;|&nbsp;<a asp-action="Delete" asp-route-id="@item.ClientID">Delete</a>-->
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
            }
            else
            {

            <h2>Please Login to continue...</h2>
            }