Microbe/Models/ReportModels/ReportDefinitions.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Microbe.Models.ReportModels
{
    public class ReportDefinitions
    {
        [Key]
        public int ReportDefinitionID { get; set; }
        public string ReportType { get; set; }
        public string DefinitionDesc { get; set; }
        public string ReportFunction { get; set; }
        public ICollection<SubReportDefinitions> SubReportDefinitions { get; set; }

        public string ModifiedBy { get; set; }
        public DateTime createDate { get; set; }
        public DateTime modifiedDate { get; set; }

    }
}

Microbe/Controllers/ReportDefinitionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microbe.Data;
using Microbe.Models.ReportModels;

namespace Microbe.Controllers
{
    public class ReportDefinitionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReportDefinitionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ReportDefinitions
        public async Task<IActionResult> Index()
        {
            return View(await _context.ReportDefinitions.ToListAsync());
        }

        // GET: ReportDefinitions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportDefinitions = await _context.ReportDefinitions
                .SingleOrDefaultAsync(m => m.ReportDefinitionID == id);
            if (reportDefinitions == null)
            {
                return NotFound();
            }

            return View(reportDefinitions);
        }

        // GET: ReportDefinitions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ReportDefinitions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReportDefinitionID,ReportType,DefinitionDesc,ReportFunction,ModifiedBy,createDate,modifiedDate")] ReportDefinitions reportDefinitions)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reportDefinitions);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reportDefinitions);
        }

        // GET: ReportDefinitions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportDefinitions = await _context.ReportDefinitions.SingleOrDefaultAsync(m => m.ReportDefinitionID == id);
            if (reportDefinitions == null)
            {
                return NotFound();
            }
            return View(reportDefinitions);
        }

        // POST: ReportDefinitions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReportDefinitionID,ReportType,DefinitionDesc,ReportFunction,ModifiedBy,createDate,modifiedDate")] ReportDefinitions reportDefinitions)
        {
            if (id != reportDefinitions.ReportDefinitionID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reportDefinitions);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReportDefinitionsExists(reportDefinitions.ReportDefinitionID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reportDefinitions);
        }

        // GET: ReportDefinitions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportDefinitions = await _context.ReportDefinitions
                .SingleOrDefaultAsync(m => m.ReportDefinitionID == id);
            if (reportDefinitions == null)
            {
                return NotFound();
            }

            return View(reportDefinitions);
        }

        // POST: ReportDefinitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reportDefinitions = await _context.ReportDefinitions.SingleOrDefaultAsync(m => m.ReportDefinitionID == id);
            _context.ReportDefinitions.Remove(reportDefinitions);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReportDefinitionsExists(int id)
        {
            return _context.ReportDefinitions.Any(e => e.ReportDefinitionID == id);
        }
    }
}

Microbe/Controllers/ReportSectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microbe.Data;
using Microbe.Models.ReportSections;

namespace Microbe.Controllers
{
    public class ReportSectionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReportSectionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ReportSections
        public async Task<IActionResult> Index()
        {
            return View(await _context.ReportSections.ToListAsync());
        }

        // GET: ReportSections/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportSections = await _context.ReportSections
                .SingleOrDefaultAsync(m => m.ReportSectionID == id);
            if (reportSections == null)
            {
                return NotFound();
            }

            return View(reportSections);
        }

        // GET: ReportSections/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ReportSections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReportSectionID,ReportDefinitionID,SectionOrder,SectionTitle,SectionDesc,ModifiedBy,createDate,modifiedDate")] ReportSections reportSections)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reportSections);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reportSections);
        }

        // GET: ReportSections/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportSections = await _context.ReportSections.SingleOrDefaultAsync(m => m.ReportSectionID == id);
            if (reportSections == null)
            {
                return NotFound();
            }
            return View(reportSections);
        }

        // POST: ReportSections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReportSectionID,ReportDefinitionID,SectionOrder,SectionTitle,SectionDesc,ModifiedBy,createDate,modifiedDate")] ReportSections reportSections)
        {
            if (id != reportSections.ReportSectionID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reportSections);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReportSectionsExists(reportSections.ReportSectionID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reportSections);
        }

        // GET: ReportSections/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportSections = await _context.ReportSections
                .SingleOrDefaultAsync(m => m.ReportSectionID == id);
            if (reportSections == null)
            {
                return NotFound();
            }

            return View(reportSections);
        }

        // POST: ReportSections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reportSections = await _context.ReportSections.SingleOrDefaultAsync(m => m.ReportSectionID == id);
            _context.ReportSections.Remove(reportSections);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReportSectionsExists(int id)
        {
            return _context.ReportSections.Any(e => e.ReportSectionID == id);
        }
    }
}

Microbe/Views/ReportDefinitions/Create.cshtml
@model Microbe.Models.ReportModels.ReportDefinitions

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>ReportDefinitions</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ReportType" class="control-label"></label>
                <input asp-for="ReportType" class="form-control" />
                <span asp-validation-for="ReportType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DefinitionDesc" class="control-label"></label>
                <input asp-for="DefinitionDesc" class="form-control" />
                <span asp-validation-for="DefinitionDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReportFunction" class="control-label"></label>
                <input asp-for="ReportFunction" class="form-control" />
                <span asp-validation-for="ReportFunction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedBy" class="control-label"></label>
                <input asp-for="ModifiedBy" class="form-control" />
                <span asp-validation-for="ModifiedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="createDate" class="control-label"></label>
                <input asp-for="createDate" class="form-control" />
                <span asp-validation-for="createDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="modifiedDate" class="control-label"></label>
                <input asp-for="modifiedDate" class="form-control" />
                <span asp-validation-for="modifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Microbe/Views/ReportDefinitions/Delete.cshtml
@model Microbe.Models.ReportModels.ReportDefinitions

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete Report Definition</h2>

<h3>Are you sure you want to delete this definition?</h3>
<div>
    <h4>ReportDefinitions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReportType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReportType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DefinitionDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DefinitionDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReportFunction)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReportFunction)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.createDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.createDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.modifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.modifiedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReportDefinitionID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Microbe/Views/ReportDefinitions/Details.cshtml
@model Microbe.Models.ReportModels.ReportDefinitions

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>ReportDefinitions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReportType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReportType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DefinitionDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DefinitionDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReportFunction)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReportFunction)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.createDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.createDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.modifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.modifiedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ReportDefinitionID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Microbe/Views/ReportDefinitions/Edit.cshtml
@model Microbe.Models.ReportModels.ReportDefinitions

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ReportDefinitions</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReportDefinitionID" />
            <div class="form-group">
                <label asp-for="ReportType" class="control-label"></label>
                <input asp-for="ReportType" class="form-control" />
                <span asp-validation-for="ReportType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DefinitionDesc" class="control-label"></label>
                <input asp-for="DefinitionDesc" class="form-control" />
                <span asp-validation-for="DefinitionDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReportFunction" class="control-label"></label>
                <input asp-for="ReportFunction" class="form-control" />
                <span asp-validation-for="ReportFunction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedBy" class="control-label"></label>
                <input asp-for="ModifiedBy" class="form-control" />
                <span asp-validation-for="ModifiedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="createDate" class="control-label"></label>
                <input asp-for="createDate" class="form-control" />
                <span asp-validation-for="createDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="modifiedDate" class="control-label"></label>
                <input asp-for="modifiedDate" class="form-control" />
                <span asp-validation-for="modifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Microbe/Views/ReportDefinitions/Index.cshtml
@model IEnumerable<Microbe.Models.ReportModels.ReportDefinitions>

@{
    ViewData["Title"] = "Defined Reports";
}
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<br />
<br />
<br />
<br />
@if (SignInManager.IsSignedIn(User))
{

    <h2>Defined Reports</h2>

    <p>
        <a asp-action="Create">Create New Defined Report</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ReportType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DefinitionDesc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReportFunction)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModifiedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.createDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.modifiedDate)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="ReportSections" asp-action="Index" asp-route-id="@item.ReportDefinitionID">@Html.DisplayFor(modelItem => item.ReportType)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DefinitionDesc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReportFunction)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.createDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.modifiedDate)
                    </td>
                    <TD>
                        <nbsp>
                            <a asp-action="Edit" asp-route-id="@item.ReportDefinitionID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.ReportDefinitionID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.ReportDefinitionID">Delete</a>
                        </nbsp>|

                    </TD>
                </tr>
            }
        </tbody>
    </table>
    <p>
        <a asp-action="Create">Create New Defined Report</a>
    </p>
}
else
{
    <h2>Please Login to continue</h2>
}